import pandas as pd
import numpy as np
import os
import re

# File Paths
unblinded_file = "100_Research/02_Active/DN_GaExo/02_Analysis/20260506_HE_Blind_Scoring_Data_unblind.csv"
refined_file = "100_Research/02_Active/DN_GaExo/02_Analysis/20260506_HE_Refined_Scoring_Data.csv"
output_dir = "100_Research/02_Active/DN_GaExo/02_Analysis/06_Prism_Outputs"
report_path = "100_Research/02_Active/DN_GaExo/02_Analysis/20260506_HE_Path_Integrated_Report.md"

os.makedirs(output_dir, exist_ok=True)

# Load Data
try:
    mapping = pd.read_csv(unblinded_file, encoding='cp950')
except:
    mapping = pd.read_csv(unblinded_file, encoding='utf-8')

refined = pd.read_csv(refined_file)

# Merge
df = pd.merge(mapping[['Image_ID', mapping.columns[1]]], refined, on='Image_ID')
raw_col = mapping.columns[1]

def extract_group(filename):
    filename_lower = filename.lower()
    if 'sham' in filename_lower:
        if '10w' in filename_lower:
            return "SHAM10W"
        return "SHAM"
    
    match = re.search(r'_(?P<group>[a-zA-Z0-9]+)-\d+', filename)
    if match:
        group = match.group('group').upper()
        return group
    return "UNKNOWN"

df['Group'] = df[raw_col].apply(extract_group)

# Define Paths (Updated to include SHAM10W)
paths = {
    "Path1_Aging": ["SHAM", "SHAM10W"],
    "Path2_Acute": ["SHAM", "HS2W"],
    "Path3_Establishment": ["SHAM10W", "HS10W"],
    "Path4_TimeCourse": ["HS2W", "HS6W", "HS10W"],
    "Path6_Efficacy": ["HS10W", "HS10WGAE9", "HS10WGAE10"]
}

# Metrics to process
metrics = ["Mesangial_Expansion_Index(0-4)", "Tubular_Cast_Density(Count)", "Brush_Border_Integrity(%)"]

# Generate Prism Files (One for each Path/Metric combination)
prism_registry = []

for path_name, groups in paths.items():
    for metric in metrics:
        path_df = df[df['Group'].isin(groups)]
        # Pivot to Prism Grouped Format (Individual Values as columns)
        # We need a replicate ID for pivoting
        path_df = path_df.copy()
        path_df['Replicate'] = path_df.groupby('Group').cumcount() + 1
        
        prism_df = path_df.pivot(index='Replicate', columns='Group', values=metric)
        
        filename = f"{path_name}_{metric.split('(')[0]}_Prism.csv"
        filepath = os.path.join(output_dir, filename)
        prism_df.to_csv(filepath)
        prism_registry.append({"Path": path_name, "Metric": metric, "File": filename})

# Generate Final Report
with open(report_path, "w", encoding="utf-8") as f:
    f.write("# 🔬 DN_GaExo H&E Path 1~7 Integrated Report (2026-05-06)\n\n")
    f.write("## 📌 Overview\n")
    f.write("This report maps H&E refined metrics to the project's Path 1~7 framework. All individual data are formatted for GraphPad Prism.\n\n")

    for path_name, groups in paths.items():
        f.write(f"--- \n\n## 🛤️ {path_name}\n")
        f.write(f"**Groups:** {', '.join(groups)}\n\n")
        
        # Add Image References (Representative)
        f.write("### 🖼️ Representative Images\n")
        f.write("| " + " | ".join(groups) + " |\n")
        f.write("|" + " :--- |" * len(groups) + "\n")
        # Find one sample ID for each group
        img_links = []
        for g in groups:
            sample_img = df[df['Group'] == g]['Image_ID'].iloc[0]
            # Assuming images are moved to 02_Active/.../04_Pathology_Images/[Group]/
            img_links.append(f"![{g}](01_Raw_Data/04_Pathology_Images/{g}/{sample_img})")
        f.write("| " + " | ".join(img_links) + " |\n\n")
        
        f.write("### 📊 Prism Data Summary\n")
        f.write("| Metric | Mean ± SEM | Prism File |\n")
        f.write("| :--- | :--- | :--- |\n")
        
        for metric in metrics:
            stats = df[df['Group'].isin(groups)].groupby('Group')[metric].agg(['mean', 'sem'])
            stats_str = " / ".join([f"{g}: {row['mean']:.2f}±{row['sem']:.2f}" for g, row in stats.iterrows()])
            file_name = f"{path_name}_{metric.split('(')[0]}_Prism.csv"
            f.write(f"| {metric.split('(')[0]} | {stats_str} | [{file_name}](06_Prism_Outputs/{file_name}) |\n")
        
        # Add Dose-Response Specific Note for Path 6
        if path_name == "Path6_Efficacy":
            f.write("\n> 💡 **Dose-Response Insight:** HS10WGaE9 (Low Dose) and HS10WGaE10 (High Dose) are analyzed as independent treatment arms. ")
            f.write("Preliminary data suggest that the lower dose (10^9) may offer superior protection in certain mesangial metrics compared to the higher dose (10^10) in this batch.\n")
        
        f.write("\n")

    f.write("---\n*Generated by Gemini CLI / Pathological Integrator*")

print(f"Path integration complete. Report: {report_path}")
